/* Theme collaboration diagram on people.html.
   Data comes from data/collaboration.js, generated by network/build_collaboration.py.
   Nothing here is hand-maintained.

   Interaction: hovering or focusing a theme or a link explains it in the readout;
   choosing a theme filters the people directory below using the existing group filter. */
(function () {
    const data = window.WPE_COLLABORATION;
    const host = document.getElementById('collab');
    if (!data || !host) return;

    const NS = 'http://www.w3.org/2000/svg';
    const COLOUR = {
        'Indoor Air': '#77AAD4',
        'BioResources': '#6F8AC6',
        'Sanitation & WASH': '#8AC9C1',
        'Water': '#5FA8B8'
    };
    const W = 680, H = 420, CX = W / 2, CY = H / 2 - 5, R = 140;
    const el = (name, attrs, text) => {
        const n = document.createElementNS(NS, name);
        for (const k in attrs) n.setAttribute(k, attrs[k]);
        if (text !== undefined) n.textContent = text;
        return n;
    };
    const plural = (n, one, many) => n + ' ' + (n === 1 ? one : many);

    const nodes = data.nodes.map((n, i, arr) => {
        const a = (Math.PI * 2 * i) / arr.length - Math.PI / 2;
        return Object.assign({}, n, { x: CX + R * Math.cos(a), y: CY + R * Math.sin(a), angle: a });
    });
    const at = id => nodes.find(n => n.id === id);
    const index = id => nodes.findIndex(n => n.id === id);
    const maxLink = Math.max(1, ...data.links.map(l => l.value));
    const maxWithin = Math.max(1, ...nodes.map(n => n.within));

    const svg = el('svg', {
        viewBox: `0 0 ${W} ${H}`, class: 'collab-svg', role: 'group',
        'aria-label': 'Co-authorship between the four research themes. The same figures are in the table below.'
    });
    const linkLayer = el('g', {}), nodeLayer = el('g', {});
    svg.appendChild(linkLayer); svg.appendChild(nodeLayer);

    // ---- links -------------------------------------------------------------
    let opposite = 0;
    const linkEls = [];
    data.links.slice().sort((a, b) => b.value - a.value).forEach(l => {
        const s = at(l.source), t = at(l.target);
        if (!s || !t) return;
        const mx = (s.x + t.x) / 2, my = (s.y + t.y) / 2;
        // opposite nodes would both run through the centre and collide, so bow them aside
        const gap = Math.abs(index(l.source) - index(l.target));
        const apart = Math.min(gap, nodes.length - gap);
        let cx, cy;
        if (apart > 1) {
            const dx = t.x - s.x, dy = t.y - s.y, len = Math.hypot(dx, dy) || 1;
            const side = (opposite++ % 2) ? 1 : -1;
            cx = mx + (-dy / len) * 70 * side;
            cy = my + (dx / len) * 70 * side;
        } else {
            cx = mx + (CX - mx) * 0.45;
            cy = my + (CY - my) * 0.45;
        }
        const lx = 0.25 * s.x + 0.5 * cx + 0.25 * t.x;
        const ly = 0.25 * s.y + 0.5 * cy + 0.25 * t.y;
        const d = `M${s.x},${s.y} Q${cx},${cy} ${t.x},${t.y}`;
        const g = el('g', { class: 'collab-link-g' });
        g.appendChild(el('path', {
            d: d, fill: 'none',
            stroke: l.value ? '#8aa4bb' : '#c7ced6',
            'stroke-opacity': l.value ? 0.55 : 1,
            'stroke-linecap': 'round',
            'stroke-dasharray': l.value ? 'none' : '5 6',
            'stroke-width': l.value ? 2 + (l.value / maxLink) * 16 : 2
        }));
        g.appendChild(el('text', {
            x: lx, y: ly - 5, 'text-anchor': 'middle',
            class: l.value ? 'collab-value' : 'collab-zero'
        }, l.value ? l.value : 'none'));
        linkLayer.appendChild(g);
        linkEls.push({ g: g, link: l });
    });

    // ---- nodes -------------------------------------------------------------
    const nodeEls = [];
    nodes.forEach(n => {
        const r = 24 + (n.within / maxWithin) * 20;
        const partners = data.links.filter(l => l.source === n.id || l.target === n.id);
        const withPeople = partners.filter(l => l.value).map(l =>
            (l.source === n.id ? l.target : l.source) + ' ' + l.value);
        const g = el('g', {
            class: 'collab-node', tabindex: '0', role: 'button',
            'aria-label': `${n.id}: ${plural(n.people, 'person', 'people')} on this page, ` +
                `${plural(n.within, 'output', 'outputs')} co-authored within the theme` +
                (withPeople.length ? ', and with ' + withPeople.join(', ') : '') +
                '. Choose to filter the directory below.'
        });
        g.appendChild(el('circle', {
            cx: n.x, cy: n.y, r: r, fill: COLOUR[n.id] || '#77AAD4',
            stroke: '#fff', 'stroke-width': 3, class: 'collab-disc'
        }));
        g.appendChild(el('text', { x: n.x, y: n.y + 5, 'text-anchor': 'middle', class: 'collab-node-value' }, n.within));
        const side = Math.abs(Math.cos(n.angle)) > 0.5;
        g.appendChild(el('text', {
            x: n.x + (side ? (n.x > CX ? r + 10 : -(r + 10)) : 0),
            y: n.y + (side ? 5 : (n.y > CY ? r + 22 : -(r + 12))),
            'text-anchor': side ? (n.x > CX ? 'start' : 'end') : 'middle',
            class: 'collab-node-label'
        }, n.id));
        nodeLayer.appendChild(g);
        nodeEls.push({ g: g, node: n });
    });

    // ---- readout and highlighting -----------------------------------------
    const readout = document.createElement('p');
    readout.className = 'collab-readout';
    readout.setAttribute('aria-live', 'polite');
    const REST = 'Hover or focus a theme to see who it works with. Choose one to filter the directory below.';
    readout.textContent = REST;

    function clear() {
        host.classList.remove('is-highlighting');
        nodeEls.forEach(x => x.g.classList.remove('is-on'));
        linkEls.forEach(x => x.g.classList.remove('is-on'));
        readout.textContent = REST;
    }
    function highlightNode(n) {
        host.classList.add('is-highlighting');
        nodeEls.forEach(x => x.g.classList.toggle('is-on', x.node.id === n.id));
        linkEls.forEach(x => x.g.classList.toggle('is-on', x.link.source === n.id || x.link.target === n.id));
        const joined = data.links.filter(l => (l.source === n.id || l.target === n.id) && l.value)
            .sort((a, b) => b.value - a.value)
            .map(l => `${plural(l.value, 'output', 'outputs')} with ${l.source === n.id ? l.target : l.source}`);
        const none = data.links.filter(l => (l.source === n.id || l.target === n.id) && !l.value)
            .map(l => l.source === n.id ? l.target : l.source);
        readout.innerHTML = `<strong>${n.id}</strong>: ${plural(n.people, 'person', 'people')} on this page, ` +
            `${plural(n.within, 'output', 'outputs')} co-authored within the theme` +
            (joined.length ? ', ' + joined.join(', ') : '') +
            (none.length ? `. No co-authored outputs with ${none.join(' or ')}.` : '.');
    }
    function highlightLink(l) {
        if (!l.value) {
            host.classList.add('is-highlighting');
            linkEls.forEach(x => x.g.classList.toggle('is-on', x.link === l));
            nodeEls.forEach(x => x.g.classList.toggle('is-on', x.node.id === l.source || x.node.id === l.target));
            readout.innerHTML = `<strong>${l.source} and ${l.target}</strong>: no co-authored outputs in ${data.period}.`;
            return;
        }
        host.classList.add('is-highlighting');
        linkEls.forEach(x => x.g.classList.toggle('is-on', x.link === l));
        nodeEls.forEach(x => x.g.classList.toggle('is-on', x.node.id === l.source || x.node.id === l.target));
        readout.innerHTML = `<strong>${l.source} and ${l.target}</strong>: ${plural(l.value, 'output', 'outputs')} written together.`;
    }

    function chooseTheme(slug) {
        const btn = document.querySelector('.filter-btn[data-group="' + slug + '"]');
        if (!btn) return;
        btn.click();
        const grid = document.querySelector('.people-grid') || document.querySelector('.people-directory');
        if (grid) grid.scrollIntoView({
            behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth',
            block: 'start'
        });
    }

    nodeEls.forEach(x => {
        x.g.addEventListener('mouseenter', () => highlightNode(x.node));
        x.g.addEventListener('focus', () => highlightNode(x.node));
        x.g.addEventListener('mouseleave', clear);
        x.g.addEventListener('blur', clear);
        x.g.addEventListener('click', () => chooseTheme(x.node.slug));
        x.g.addEventListener('keydown', e => {
            if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); chooseTheme(x.node.slug); }
        });
    });
    linkEls.forEach(x => {
        x.g.addEventListener('mouseenter', () => highlightLink(x.link));
        x.g.addEventListener('mouseleave', clear);
    });

    // ---- figure, readout, collapsible table --------------------------------
    const fig = document.createElement('figure');
    fig.className = 'collab-figure';
    fig.appendChild(svg);
    const cap = document.createElement('figcaption');
    cap.textContent = 'A line joins two themes when an output was written by people from both; its width is how many. ' +
        'The number in a circle is outputs co-authored within that theme.';
    fig.appendChild(cap);

    const details = document.createElement('details');
    details.className = 'collab-details';
    details.innerHTML = '<summary>Show the figures as a table</summary>' +
        '<table class="collab-table">' +
        '<caption>Co-authored outputs, ' + data.period + '</caption>' +
        '<thead><tr><th scope="col">Themes</th><th scope="col" class="num">Outputs</th></tr></thead><tbody>' +
        data.links.slice().sort((a, b) => b.value - a.value).map(l =>
            `<tr><th scope="row">${l.source} and ${l.target}</th><td class="num">${l.value}</td></tr>`).join('') +
        data.nodes.map(n =>
            `<tr><th scope="row">Within ${n.id}</th><td class="num">${n.within}</td></tr>`).join('') +
        '</tbody></table>';

    const note = document.createElement('p');
    note.className = 'collab-note';
    note.innerHTML = 'Built from ' + data.counts.outputs.toLocaleString('en-GB') + ' research outputs, ' +
        data.period + ', covering ' + data.counts.staff + ' staff and ' + data.counts.students +
        ' doctoral researchers, of whom ' + data.counts.peopleMatched +
        ' appear as an author in that period. A doctoral researcher takes the theme of their supervisor. ' +
        'People who joined recently will be under-represented. Generated ' +
        new Date(data.generated).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) +
        ' by <code>network/build_collaboration.py</code>.';

    host.appendChild(fig);
    host.appendChild(readout);
    host.appendChild(details);
    host.appendChild(note);
})();
