/* Country Overshoot Days timeline.
   Data: data/overshoot.js, generated by network/build_overshoot.py from
   Global Footprint Network. Nothing here is hand-maintained. */
(function () {
    const data = window.WPE_OVERSHOOT;
    const host = document.getElementById('overshoot');
    if (!data || !host) return;

    const NS = 'http://www.w3.org/2000/svg';
    const el = (n, a, t) => {
        const e = document.createElementNS(NS, n);
        for (const k in a) e.setAttribute(k, a[k]);
        if (t !== undefined) e.textContent = t;
        return e;
    };
    const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const MONTH_START = [1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335];
    const W = 920, H = 430, L = 46, R = 26, T = 54, B = 56;
    const days = data.daysInYear;
    const x = d => L + ((d - 1) / (days - 1)) * (W - L - R);
    // earlier date = more Earths = hotter
    const colour = e => e >= 5 ? '#8E2D5A' : e >= 3 ? '#C26B3F' : e >= 2 ? '#D8A13A' : e >= 1.5 ? '#6F8AC6' : '#5FA8B8';

    const svg = el('svg', {
        viewBox: `0 0 ${W} ${H}`, class: 'os-svg', role: 'group',
        'aria-label': `Timeline of Country Overshoot Days in ${data.year}. Every country and date is also listed below.`
    });

    // months
    MONTH_START.forEach((d, i) => {
        svg.appendChild(el('line', { x1: x(d), y1: T - 12, x2: x(d), y2: H - B + 6, class: 'os-grid' }));
        svg.appendChild(el('text', { x: x(d) + 4, y: H - B + 22, class: 'os-month' }, MONTHS[i]));
    });
    svg.appendChild(el('line', { x1: L, y1: H - B + 6, x2: W - R, y2: H - B + 6, class: 'os-axis' }));

    // global overshoot day
    const gm = /(\d{1,2}) (\w+)/.exec(data.globalOvershootDay);
    if (gm) {
        const gd = new Date(Date.UTC(data.year, MONTHS.indexOf(gm[2].slice(0, 3)), +gm[1]));
        const gdoy = Math.floor((gd - Date.UTC(data.year, 0, 0)) / 86400000);
        svg.appendChild(el('line', { x1: x(gdoy), y1: T - 26, x2: x(gdoy), y2: H - B + 6, class: 'os-global' }));
        svg.appendChild(el('text', { x: x(gdoy), y: T - 32, class: 'os-global-label', 'text-anchor': 'middle' },
            `Earth Overshoot Day, ${data.globalOvershootDay.replace(' ' + data.year, '')}`));
    }

    // one dot per country, stacked where dates collide
    const lanes = [];
    const dots = [];
    data.countries.forEach(c => {
        let lane = 0;
        while (lanes[lane] !== undefined && x(c.dayOfYear) - lanes[lane] < 13) lane++;
        lanes[lane] = x(c.dayOfYear);
        const cy = T + lane * 15;
        const g = el('g', {
            class: 'os-dot', tabindex: '0', role: 'button',
            'aria-label': `${c.country}: ${c.formatted}, ${c.earths} Earths`
        });
        g.appendChild(el('circle', { cx: x(c.dayOfYear), cy: cy, r: 5.5, fill: colour(c.earths) }));
        dots.push({ g, c, cx: x(c.dayOfYear), cy });
        svg.appendChild(g);
    });

    // readout
    const readout = document.createElement('p');
    readout.className = 'os-readout';
    readout.setAttribute('aria-live', 'polite');
    const REST = `${data.countries.length} countries, earliest to latest. Hover, focus or choose a dot for the detail.`;
    readout.textContent = REST;

    function show(c) {
        host.classList.add('is-on');
        dots.forEach(d => d.g.classList.toggle('is-sel', d.c === c));
        readout.innerHTML = `<strong>${c.country}</strong> &mdash; ${c.formatted} ${data.year}. ` +
            `If everyone lived like this, humanity would need <strong>${c.earths} Earths</strong>.`;
    }
    function clear() {
        host.classList.remove('is-on');
        dots.forEach(d => d.g.classList.remove('is-sel'));
        readout.textContent = REST;
    }
    dots.forEach(d => {
        d.g.addEventListener('mouseenter', () => show(d.c));
        d.g.addEventListener('focus', () => show(d.c));
        d.g.addEventListener('mouseleave', clear);
        d.g.addEventListener('blur', clear);
    });

    // controls
    const controls = document.createElement('div');
    controls.className = 'os-controls';
    controls.innerHTML =
        '<label class="os-search"><span>Search</span>' +
        '<input type="search" id="os-q" placeholder="e.g. United Kingdom" autocomplete="off"></label>' +
        '<div class="os-months" role="group" aria-label="Filter by month">' +
        '<button type="button" class="os-mbtn is-active" data-month="all">All</button>' +
        MONTHS.map((m, i) => `<button type="button" class="os-mbtn" data-month="${i}">${m}</button>`).join('') +
        '</div>';

    const list = document.createElement('ul');
    list.className = 'os-list';
    const count = document.createElement('p');
    count.className = 'os-count';

    let month = 'all', q = '';
    function apply() {
        const shown = data.countries.filter(c =>
            (month === 'all' || new Date(c.date).getUTCMonth() === +month) &&
            (!q || c.country.toLowerCase().includes(q)));
        const keep = new Set(shown.map(c => c.country));
        dots.forEach(d => d.g.classList.toggle('is-dim', !keep.has(d.c.country)));
        list.innerHTML = shown.map(c =>
            `<li><span class="os-c">${c.country}</span>` +
            `<span class="os-d">${c.formatted}</span>` +
            `<span class="os-e" style="color:${colour(c.earths)}">${c.earths} Earths</span></li>`).join('')
            || '<li class="os-empty">No countries match.</li>';
        count.textContent = shown.length === data.countries.length
            ? `All ${data.countries.length} countries`
            : `${shown.length} of ${data.countries.length} countries`;
    }
    controls.addEventListener('click', e => {
        const b = e.target.closest('.os-mbtn');
        if (!b) return;
        controls.querySelectorAll('.os-mbtn').forEach(x => x.classList.remove('is-active'));
        b.classList.add('is-active');
        month = b.dataset.month;
        apply();
    });
    controls.addEventListener('input', e => {
        if (e.target.id !== 'os-q') return;
        q = e.target.value.trim().toLowerCase();
        apply();
    });

    const fig = document.createElement('figure');
    fig.className = 'os-figure';
    fig.appendChild(svg);
    const cap = document.createElement('figcaption');
    cap.textContent = 'Each dot is a country, placed on the date the world would exhaust its annual ' +
        'budget of resources if everyone consumed at that country\'s rate. Colour follows the number of Earths required.';
    fig.appendChild(cap);

    const none = document.createElement('div');
    none.className = 'os-none';
    none.innerHTML = '<h3>Countries that never reach one</h3>' +
        `<p>${data.noOvershootDay.length} of the countries in the source consume less per person than the world ` +
        'can regenerate per person, so no overshoot day exists for them. The figure is the portion of one Earth ' +
        'that would be needed if everyone lived that way.</p><ul class="os-none-list">' +
        data.noOvershootDay.map(n => `<li><span>${n.country}</span><span>${n.portionOfEarth}%</span></li>`).join('') +
        '</ul>';

    const note = document.createElement('p');
    note.className = 'os-note';
    note.innerHTML = `Source: <a href="${data.sourceUrl}" target="_blank" rel="noopener">${data.source}</a>, ` +
        `${data.year} edition. ${data.method} Generated ` +
        new Date(data.generated).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) +
        ' by <code>network/build_overshoot.py</code>.';

    host.appendChild(fig);
    host.appendChild(readout);
    host.appendChild(controls);
    host.appendChild(count);
    host.appendChild(list);
    host.appendChild(none);
    host.appendChild(note);
    apply();
})();
