"""Generate data/overshoot.js: Country Overshoot Days, from Global Footprint Network.

    python3 network/build_overshoot.py            # fetch and rebuild
    python3 network/build_overshoot.py --cached   # reuse the last download

Source: https://overshoot.footprintnetwork.org/newsroom/country-overshoot-days/

Method, as published by Global Footprint Network: a country's overshoot day is
    365 x (global biocapacity per person / that country's Ecological Footprint per person)
so the number of Earths required is 365 / day-of-year. Countries whose footprint per
person is below world biocapacity per person never reach an overshoot day; the source
lists those separately as a percentage of one Earth.

The previous version of this chart kept its data as a hand-edited array inside the blog
post. The array was truncated at some point, which left the page rendering nothing and
printing raw JavaScript to the screen. Hence this script: do not hand-edit the output.
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "overshoot.json"
CACHE = Path("/tmp/wpe_country_overshoot.html")
URL = "https://overshoot.footprintnetwork.org/newsroom/country-overshoot-days/"
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/141.0 Safari/537.36")
YEAR = 2026
DAYS_IN_YEAR = 366 if (YEAR % 4 == 0 and YEAR % 100 != 0) or YEAR % 400 == 0 else 365


def fetch(use_cache: bool) -> str:
    if use_cache and CACHE.exists():
        return CACHE.read_text(encoding="utf-8", errors="ignore")
    req = urllib.request.Request(URL, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        body = r.read().decode("utf-8", "ignore")
    CACHE.write_text(body, encoding="utf-8")
    return body


def cells(row: str) -> list:
    return [re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", c))).strip()
            for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, re.S)]


def parse(page: str):
    dated, none = {}, {}
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", page, re.S):
        c = cells(row)
        if len(c) < 2 or not c[0] or c[0].lower().startswith("country"):
            continue
        name, value = c[0], c[1]
        m = re.search(r"([A-Z][a-z]+) (\d{1,2}), (\d{4})", value)
        if m:
            date = dt.date(int(m.group(3)), dt.datetime.strptime(m.group(1), "%B").month, int(m.group(2)))
            if date.year == YEAR:
                dated[name] = date          # the page repeats each row; a dict de-duplicates
        elif re.fullmatch(r"\d{1,3}%", value):
            none[name] = int(value.rstrip("%"))
    return dated, none


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cached", action="store_true", help="reuse the last download")
    args = ap.parse_args()

    page = fetch(args.cached)
    dated, none = parse(page)
    if len(dated) < 40:
        print(f"only {len(dated)} countries parsed; the source layout has probably changed", file=sys.stderr)
        return 1

    countries = []
    for name, date in sorted(dated.items(), key=lambda kv: kv[1]):
        doy = date.timetuple().tm_yday
        countries.append({
            "country": name,
            "date": date.isoformat(),
            "formatted": f"{date.day} {date.strftime('%B')}",
            "dayOfYear": doy,
            "earths": round(DAYS_IN_YEAR / doy, 1),
        })

    payload = {
        "year": YEAR,
        "generated": dt.date.today().isoformat(),
        "source": "Global Footprint Network, Country Overshoot Days",
        "sourceUrl": URL,
        "daysInYear": DAYS_IN_YEAR,
        "globalOvershootDay": "30 July 2026",
        "method": ("A country's overshoot day is 365 x (world biocapacity per person / that country's "
                   "Ecological Footprint per person). The Earths figure is 365 divided by the day of the year."),
        "countries": countries,
        "noOvershootDay": [{"country": k, "portionOfEarth": v}
                           for k, v in sorted(none.items(), key=lambda kv: kv[1])],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    OUT.with_suffix(".js").write_text(
        "/* Generated by network/build_overshoot.py - do not edit by hand. */\n"
        "window.WPE_OVERSHOOT = " + json.dumps(payload, indent=2) + ";\n", encoding="utf-8")

    print(f"{len(countries)} countries with a {YEAR} overshoot day, "
          f"{len(payload['noOvershootDay'])} without one")
    print(f"  earliest: {countries[0]['country']} {countries[0]['formatted']} "
          f"({countries[0]['earths']} Earths)")
    print(f"  latest:   {countries[-1]['country']} {countries[-1]['formatted']} "
          f"({countries[-1]['earths']} Earths)")
    print(f"wrote {OUT.relative_to(ROOT)} and {OUT.with_suffix('.js').relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
